# Package metadata for Telu icons for Callisto
# All fields are optional; defaults will be used if not specified

PACKAGE_AUTHOR="qkmaxware"
PACKAGE_VERSION="1.0.0"
PACKAGE_LICENSE="MIT"
PACKAGE_DESCRIPTION="Telu icon theme by vinceliuice (https://github.com/vinceliuice) customized for Callisto OS"