# Package metadata for reset-home 
# All fields are optional; defaults will be used if not specified

PACKAGE_AUTHOR="qkmaxware"
PACKAGE_VERSION="1.0.0"
PACKAGE_LICENSE="MIT"
PACKAGE_DESCRIPTION="Simple console utility to reset configuration of your home directory to default values from /etc/skel."
PACKAGE_DEPENDS=""