# Package metadata for callisto-icons
# All fields are optional; defaults will be used if not specified

PACKAGE_AUTHOR="qkmaxware"
PACKAGE_VERSION="1.0.0"
PACKAGE_LICENSE="MIT"
PACKAGE_DESCRIPTION="OS Icons for Callisto OS"
PACKAGE_DEPENDS=""